apply plugin: 'application'

[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
java.sourceCompatibility = java.targetCompatibility = appJavaCompatibility

application.mainClass = 'io.github.pixeldungeonmultiplayer.shattered.server.headless.HeadlessDesktopLauncher'

processResources {
    from new File(project(':core').projectDir, '/src/main/assets')
    from new File(project(':desktop').projectDir, '/src/main/assets')
}

dependencies {
    implementation project(':core')
    implementation project(':desktop')
    implementation "org.json:json:20170516"
    implementation "com.badlogicgames.gdx:gdx-backend-headless:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
    runtimeOnly "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
    runtimeOnly "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-desktop"
}

tasks.named('run', JavaExec) {
    workingDir = rootProject.projectDir
    systemProperty 'Specification-Version', appVersionName + '-HEADLESS'
    systemProperty 'Implementation-Version', appVersionCode
    standardInput = System.in
}
