apply plugin: 'java-library'

[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
java.sourceCompatibility = java.targetCompatibility = appJavaCompatibility

dependencies {
    api project(':SPD-classes')
    implementation project(':services')
    //implementation 'org.json:json:20240303'
    //implementation ('org.json:json:20090211')

    // old JSON Library for Android support
    // https://github.com/stleary/JSON-java/wiki/JSON-Java-for-Android-developers
    // use version like in SPD-classes module
    //noinspection GradleDependency
    implementation "org.json:json:20170516"
    implementation ('org.jetbrains:annotations:24.1.0')

    testImplementation project(':headless-client')
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.2'
}

test {
    useJUnitPlatform()
}
